# Generated by Django 2.2.10 on 2020-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savepath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_path', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_width', models.IntegerField(default=2)),
                ('name_width', models.IntegerField(default=2)),
                ('price_width', models.IntegerField(default=2)),
                ('release_date_width', models.IntegerField(default=2)),
                ('lte_exists_width', models.IntegerField(default=2)),
                ('id_name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price_name', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lte_exists_name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_num', models.IntegerField(default=1)),
                ('name_num', models.IntegerField(default=2)),
                ('price_num', models.IntegerField(default=3)),
                ('release_num', models.IntegerField(default=4)),
                ('lte_num', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Параметры таблицы',
                'verbose_name_plural': 'Параметры таблиц',
            },
        ),
    ]
