# Generated by Django 2.2.10 on 2020-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepath',
            name='name_path',
        ),
        migrations.AddField(
            model_name='savepath',
            name='field_name',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
