# Generated by Django 2.2.10 on 2020-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200822_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepath',
            name='field_name',
            field=models.FilePathField(blank=True, null=True, path=None),
        ),
    ]
