# Generated by Django 2.2.10 on 2020-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='routes',
            field=models.ManyToManyField(to='project_bus.Route'),
        ),
    ]
