# Generated by Django 2.2.10 on 2020-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_bus', '0003_auto_20200815_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
